sudo: required
services:
  - docker

before_install:
  - docker build -t yuvanswomb13/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true yuvanswomb13/docker-react npm run test -- --coverage